### ISSUE TITLE
Please give some guide

### ISSUE THREAD

**Issue by 7x7x7eq51** [gomodules/notify#31]
Please give us some guide, no document how to using it?

Some example for this, please!

Thank so much!

**Comment by tamalsaha** [comment]
Thanks for your interest in this library. The interface is defined here: https://github.com/appscode/go-notify/blob/master/types.go

To instantiate the notifier, you can use https://github.com/appscode/go-notify/blob/master/unified/notifier.go package. 

The credentials can be read from ENV variable or from a `map` using LoaderFunc . 

You can see an example here: https://github.com/appscode/kubed/blob/master/pkg/eventer/forwarder.go#L41

In this example, we load the credential data from a  Kubernetes secret. Here is the code: https://github.com/appscode/kubed/blob/master/pkg/operator/operator.go#L359

**Comment by 7x7x7eq51** [comment]
@tamalsaha  thank you,

I will do something now!

And feedback some example code here.

**Comment by 7x7x7eq51** [comment]
@tamalsaha 

About "The credentials can be read from ENV variable or from a map using LoaderFunc ", please explain more this. Because i don't know your config schema!

Thanks you!

**Comment by tamalsaha** [comment]
For each notifier type. you will see 2 things : UID and a Options struct with `envconfig` tag. The key for Env var or the map are `${UID}_${tag}` (all caps). For example for Hipchat, https://github.com/appscode/go-notify/blob/master/hipchat/chat.go#L20

The keys are `HIPCHAT_AUTH_TOKEN` etc .

**Comment by 7x7x7eq51** [comment]
Yes, I understand now!
```golang
envconfig.Load(UID, &opt, loader)
```
This code loading config with prefix is UID.

**Comment by tamalsaha** [comment]
Yeah.

**Comment by 7x7x7eq51** [comment]
Hi @tamalsaha , please explain about this.
```
	notifier, err := unified.LoadVia(strings.ToLower(receiver.Notifier), f.notifierCred)
```
-  api.Receiver  <== what is struct and data example.
- f.notifierCred how to bind to use it?

below my error. I don't know why.
```golang
echo: http: panic serving [::1]:37858: runtime error: invalid memory address or nil pointer dereference
goroutine 36 [running]:
net/http.(*conn).serve.func1(0xc420284000)
        /home/tpt/Public/GHN/GOLANG/go/src/net/http/server.go:1726 +0xd0
panic(0xa76a40, 0xf0b790)
        /home/tpt/Public/GHN/GOLANG/go/src/runtime/panic.go:505 +0x229
git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/appscode/envconfig.Load(0xb41585, 0x8, 0xa09ae0, 0xc42026c900, 0x0, 0x4ed377, 0xbb9680)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/appscode/envconfig/envconfig.go:170 +0x155
git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/appscode/go-notify/telegram.Load(0x0, 0x2, 0x2, 0x16)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/appscode/go-notify/telegram/chat.go:44 +0x72
git.ecomeasy.asia/mimp/bot-notify/pkg/eventer.(*EventForwarder).Notify(0xc4201a17b8, 0xc4201e3006, 0x7, 0xb4689f, 0x10, 0xb475e1, 0x11, 0xb41585, 0x8, 0xc42028a460, ...)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/pkg/eventer/main.go:37 +0xb9
git.ecomeasy.asia/mimp/bot-notify/apps/apis.wooHook(0xbc7920, 0xc42026a4d0, 0xc4201cfdc0, 0xc4201d7480)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/apps/apis/app.go:28 +0x2db
git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo.(*Echo).Add.func1(0xbc7920, 0xc42026a4d0, 0x4, 0xc4201d7485)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo/echo.go:482 +0x87
git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo.(*Echo).ServeHTTP(0xc4201b81c0, 0xbbf1a0, 0xc4201de7e0, 0xc420280100)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo/echo.go:594 +0x250
main.main.func1(0xbc7920, 0xc42026a3f0, 0xb4e56c, 0x1b)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/main.go:68 +0x339
git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo.(*Echo).Add.func1(0xbc7920, 0xc42026a3f0, 0x1b, 0x0)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo/echo.go:482 +0x87
git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo/middleware.CORSWithConfig.func1.1(0xbc7920, 0xc42026a3f0, 0x11, 0x0)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo/middleware/cors.go:113 +0x324
git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo/middleware.SecureWithConfig.func1.1(0xbc7920, 0xc42026a3f0, 0xc, 0xc4201d7500)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo/middleware/secure.go:113 +0x292
git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo/middleware.RequestIDWithConfig.func1.1(0xbc7920, 0xc42026a3f0, 0x4, 0xc4201d7485)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo/middleware/request_id.go:57 +0x144
git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo.(*Echo).ServeHTTP.func1(0xbc7920, 0xc42026a3f0, 0x0, 0xc4201e6000)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo/echo.go:586 +0x109
git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo/middleware.RemoveTrailingSlashWithConfig.func1.1(0xbc7920, 0xc42026a3f0, 0xc42026a3f0, 0xb68ed8)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo/middleware/slash.go:116 +0x189
git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo.(*Echo).ServeHTTP(0xc4201b8380, 0xbbff60, 0xc4201e42a0, 0xc420280100)
        /home/tpt/Public/GHN/GOLANG/WORK/src/git.ecomeasy.asia/mimp/bot-notify/vendor/github.com/labstack/echo/echo.go:594 +0x250
net/http.serverHandler.ServeHTTP(0xc4201dcb60, 0xbbff60, 0xc4201e42a0, 0xc420280100)
        /home/tpt/Public/GHN/GOLANG/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420284000, 0xbc0560, 0xc42020a2c0)
        /home/tpt/Public/GHN/GOLANG/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /home/tpt/Public/GHN/GOLANG/go/src/net/http/server.go:2795 +0x27b
```
please!
Thank so much!

My code have been custom as lib: 

```golang
package eventer

import (
	"strings"
	"sync"

	"github.com/2tgroup/go-notify"
	"github.com/2tgroup/go-notify/unified"
	"github.com/appscode/envconfig"
)

type (
	EventForwarder struct {
		notifierCred envconfig.LoaderFunc
		lock         sync.RWMutex
	}
	Notifier struct {
		From string
		To   []string
	}
)

//Configure run config with load ENV
func (f *EventForwarder) Configure(notifierCred envconfig.LoaderFunc) {
	f.lock.Lock()
	defer f.lock.Unlock()
	f.notifierCred = notifierCred
}

//Notify send notify
func (f *EventForwarder) Notify(emailSub, chatSub, body string, receiver *Notifier) error {

	notifier, err := unified.LoadVia(strings.ToLower(receiver.From), f.notifierCred)

	if err != nil {
		return err
	}
	switch n := notifier.(type) {
	case notify.ByEmail:
		return n.To(receiver.From, receiver.To[1:]...).
			WithSubject(emailSub).
			WithBody(body).
			WithNoTracking().
			Send()
	case notify.BySMS:
		return n.To(receiver.From, receiver.To[1:]...).
			WithBody(emailSub).
			Send()
	case notify.ByChat:
		return n.To(receiver.From, receiver.To[1:]...).
			WithBody(chatSub).
			Send()
	case notify.ByPush:
		return n.To(receiver.To...).
			WithBody(chatSub).
			Send()
	}
	return nil
}

```
How I use it.

```golang
dataPost := new(WooEcomHook)
	if err := c.Bind(dataPost); err != nil {
		fmt.Println("ERR:", err)
		return c.JSON(http.StatusBadRequest, "Can not parse json!")
	}

	eventCc := new(eventer.Notifier) //&eventer.Notifier{From: "telegram", To: []string{"tpt_rich", "ece_emiso_bot"}}
	eventCc.From = "telegram"
	eventCc.To = []string{"tpt_rich", "ece_emiso_bot"}

	eventSend := new(eventer.EventForwarder)

	//List send notify

	errorSend := eventSend.Notify(dataPost.Status, "We get new order", "We have new order", eventCc)
```

**Comment by 7x7x7eq51** [comment]
After debug I think crash because it can not convert .
```golang
echo: http: panic serving [::1]:42172: interface conversion: *telegram.client is not notify.ByChat
```
